In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('retail_sales.csv.csv')
df.head()

  Order_ID  Order_Date   Product     Category  Quantity  Sales   Cost  Region
0   ORD001  05-01-2026    Laptop  Electronics         1  55000  48000   Delhi
1   ORD002  07-01-2026     Mouse  Accessories         2   1600   1000  Mumbai
2   ORD003  09-01-2026     Chair    Furniture         2   9000   6000   Delhi
3   ORD004  12-01-2026  Keyboard  Accessories         1   2500   1700    Pune
4   ORD005  15-01-2026   Monitor  Electronics         1  18000  14500  Mumbai

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    30 non-null     object
 1   Order_Date  30 non-null     object
 2   Product     30 non-null     object
 3   Category    30 non-null     object
 4   Quantity    30 non-null     int64
 5   Sales       30 non-null     int64
 6   Cost        30 non-null     int64
 7   Region      30 non-null     object
dtypes: int64(3), object(5)
memory usage: 2.0+ KB

In [8]:
df.isnull().sum()/df.shape[0]*100

Order_ID      0.0
Order_Date    0.0
Product       0.0
Category      0.0
Quantity      0.0
Sales         0.0
Cost          0.0
Region        0.0
dtype: float64

In [10]:
df.shape

(30, 8)

In [12]:
df.columns

Index(['Order_ID', 'Order_Date', 'Product', 'Category', 'Quantity', 'Sales',
       'Cost', 'Region'],
      dtype='object')

In [14]:
len(df['Order_ID'].unique())

30

In [16]:
df[df.duplicated()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Product, Category, Quantity, Sales, Cost, Region]
Index: []

In [18]:
df['Order_Date']=pd.to_datetime(df['Order_Date'],format='%d-%m-%Y')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    30 non-null     object
 1   Order_Date  30 non-null     datetime64[ns]
 2   Product     30 non-null     object
 3   Category    30 non-null     object
 4   Quantity    30 non-null     int64
 5   Sales       30 non-null     int64
 6   Cost        30 non-null     int64
 7   Region      30 non-null     object
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 2.0+ KB

# What products are present in our dataset, and how many different products do we have?

In [23]:
df['Product'].unique()

array(['Laptop', 'Mouse', 'Chair', 'Keyboard', 'Monitor', 'Desk',
       'Headphones', 'Printer'], dtype=object)

# How many orders/records belong to each product?

In [27]:
df.head(2)

  Order_ID Order_Date Product     Category  Quantity  Sales   Cost  Region
0   ORD001 2026-01-05  Laptop  Electronics         1  55000  48000   Delhi
1   ORD002 2026-01-07   Mouse  Accessories         2   1600   1000  Mumbai

In [29]:
df['Product'].value_counts()

Product
Laptop        4
Mouse         4
Chair         4
Monitor       4
Desk          4
Headphones    4
Keyboard      3
Printer       3
Name: count, dtype: int64

# how many units of each product were sold.

In [32]:
df.groupby(['Product'])['Quantity'].sum()

Product
Chair         8
Desk          5
Headphones    8
Keyboard      4
Laptop        5
Monitor       5
Mouse         8
Printer       4
Name: Quantity, dtype: int64

# Which product generated the highest total sales?

In [35]:
df.groupby(['Product'])['Sales'].sum()

Product
Chair          36000
Desk           35200
Headphones     20300
Keyboard       10000
Laptop        275000
Monitor        90500
Mouse           6400
Printer        48500
Name: Sales, dtype: int64

# How much total sales did each category generate?

In [38]:
df.groupby(['Category'])['Sales'].sum()

Category
Accessories     36700
Electronics    414000
Furniture       71200
Name: Sales, dtype: int64

# Profit

In [41]:
df['Profit']=df['Sales']-df['Cost']

In [43]:
df.head(2)

,Order_ID,Order_Date,Product,Category,Quantity,Sales,Cost,Region,Profit
0,ORD001,2026-01-05,Laptop,Electronics,1,55000,48000,Delhi,7000
1,ORD002,2026-01-07,Mouse,Accessories,2,1600,1000,Mumbai,600

# Which product generates the highest total profit?

In [46]:
df.groupby(['Product'])['Profit'].sum()

Product
Chair         12000
Desk          10200
Headphones     7200
Keyboard       3200
Laptop        35000
Monitor       18000
Mouse          2400
Printer       10500
Name: Profit, dtype: int64

In [48]:
df['Profit_Margin']=(df['Profit']/df['Sales'])*100

In [50]:
df.head(2)

,Order_ID,Order_Date,Product,Category,Quantity,Sales,Cost,Region,Profit,Profit_Margin
0,ORD001,2026-01-05,Laptop,Electronics,1,55000,48000,Delhi,7000,12.727273
1,ORD002,2026-01-07,Mouse,Accessories,2,1600,1000,Mumbai,600,37.500000

# What is the average profit margin for each product?

In [53]:
df.groupby(['Product'])['Profit_Margin'].mean()

Product
Chair         33.333333
Desk          29.067460
Headphones    35.307692
Keyboard      32.000000
Laptop        12.729377
Monitor       19.988739
Mouse         37.500000
Printer       21.888889
Name: Profit_Margin, dtype: float64

# What is the average profit margin for each category?

In [56]:
df.groupby(['Category'])['Profit_Margin'].mean()

Category
Accessories    35.202797
Electronics    17.867194
Furniture      31.200397
Name: Profit_Margin, dtype: float64

# How are sales performing month by month?

In [59]:
df['Month']=df['Order_Date'].dt.month

In [61]:
df.groupby(['Month'])['Sales'].sum()

Month
1    110100
2    142500
3    119300
4    150000
Name: Sales, dtype: int64

In [63]:
df['Month Name']=df['Order_Date'].dt.month_name()

In [65]:
df.head(2)

,Order_ID,Order_Date,Product,Category,Quantity,Sales,Cost,Region,Profit,Profit_Margin,Month,Month Name
0,ORD001,2026-01-05,Laptop,Electronics,1,55000,48000,Delhi,7000,12.727273,1,January
1,ORD002,2026-01-07,Mouse,Accessories,2,1600,1000,Mumbai,600,37.500000,1,January

# How much profit did we make in each month?

In [68]:
df.groupby(['Month'])['Profit'].sum()

Month
1    21200
2    27900
3    24800
4    24600
Name: Profit, dtype: int64

# which month was the most profitable relative to its sales

In [71]:
df.groupby(['Month'])['Profit_Margin'].mean()

Month
1    27.551227
2    27.407611
3    28.438814
4    27.698644
Name: Profit_Margin, dtype: float64

# Which region generated the highest total sales?

In [74]:
df.groupby(['Region'])['Sales'].sum()

Region
Bangalore     95500
Delhi        243600
Hyderabad     47100
Mumbai        56100
Pune          79600
Name: Sales, dtype: int64

# most profitable region.

In [77]:
df.groupby(['Region'])['Profit'].sum()

Region
Bangalore    17600
Delhi        42700
Hyderabad    12100
Mumbai       13100
Pune         13000
Name: Profit, dtype: int64

# average profit margin by region

In [80]:
df.groupby(['Region'])['Profit_Margin'].mean()

Region
Bangalore    25.605277
Delhi        28.409005
Hyderabad    27.895238
Mumbai       29.861111
Pune         26.204558
Name: Profit_Margin, dtype: float64

In [82]:
df.groupby(['Region'])[['Sales','Profit','Profit_Margin']].mean()

                  Sales       Profit  Profit_Margin
Region
Bangalore  19100.000000  3520.000000      25.605277
Delhi      27066.666667  4744.444444      28.409005
Hyderabad   9420.000000  2420.000000      27.895238
Mumbai      9350.000000  2183.333333      29.861111
Pune       15920.000000  2600.000000      26.204558

# quantity sold by region.

In [85]:
df.groupby(['Region'])['Quantity'].sum()

Region
Bangalore     7
Delhi        20
Hyderabad     7
Mumbai        8
Pune          5
Name: Quantity, dtype: int64

In [87]:
df.groupby(['Product','Category'])['Sales'].sum()

Product     Category
Chair       Furniture       36000
Desk        Furniture       35200
Headphones  Accessories     20300
Keyboard    Accessories     10000
Laptop      Electronics    275000
Monitor     Electronics     90500
Mouse       Accessories      6400
Printer     Electronics     48500
Name: Sales, dtype: int64

In [89]:
df.groupby(['Category'])['Quantity'].sum()

Category
Accessories    20
Electronics    14
Furniture      13
Name: Quantity, dtype: int64

# average selling value per unit

In [92]:
a = df.groupby('Category')['Sales'].sum()
b = df.groupby('Category')['Quantity'].sum()

In [94]:
a/b

Category
Accessories     1835.000000
Electronics    29571.428571
Furniture       5476.923077
dtype: float64

# Product Sales Ranking

In [97]:
df.groupby('Product')['Sales'].sum().sort_values(ascending=False)

Product
Laptop        275000
Monitor        90500
Printer        48500
Chair          36000
Desk           35200
Headphones     20300
Keyboard       10000
Mouse           6400
Name: Sales, dtype: int64

# Rank products by profit

In [100]:
df.groupby(['Product'])['Profit'].sum().sort_values(ascending=False)

Product
Laptop        35000
Monitor       18000
Chair         12000
Printer       10500
Desk          10200
Headphones     7200
Keyboard       3200
Mouse          2400
Name: Profit, dtype: int64

# basic stats

In [103]:
df.describe()

,Order_Date,Quantity,Sales,Cost,Profit,Profit_Margin,Month
count,30,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,2026-02-23 20:00:00,1.566667,17396.666667,14113.333333,3283.333333,27.779102,2.400000
min,2026-01-05 00:00:00,1.000000,800.000000,500.000000,300.000000,12.500000,1.000000
25%,2026-01-27 00:00:00,1.000000,4625.000000,3050.000000,1525.000000,20.833333,1.250000
50%,2026-02-24 00:00:00,1.000000,8250.000000,5500.000000,2600.000000,31.277778,2.000000
75%,2026-03-19 06:00:00,2.000000,18000.000000,14500.000000,4000.000000,34.294872,3.000000
max,2026-04-22 00:00:00,3.000000,110000.000000,96000.000000,14000.000000,37.500000,4.000000
std,NaN,0.678911,23587.394110,20822.927240,2869.108156,8.420468,1.101723